### PR TITLE
Add libmongo-client rosdep for Nix

### LINKED ISSUE #295: Fail to build ur10e-moveit-config
```
nix build github:lopsided98/nix-ros-overlay/b923476c0a96d0a13991b22c9b61c180e3df4b6f#noetic.ur10e-moveit-config
```

gives

```
error: evaluation aborted with the following error message: 'Function called without required argument "warehouse-ros-mongo" at /nix/store/gybs2r1g2jnnihh6yhjwahy0c0lvlmjc-source/distros/noetic/ur10e-moveit-config/default.nix:5'
```

it seems [`warehouse_ros_mongo`](https://github.com/ros-planning/warehouse_ros_mongo) is missing to the overlay.

### PR DESCRIPTION
**Pull request by GuillaumeDesforges**
Step to fix https://github.com/lopsided98/nix-ros-overlay/issues/295

### CODE REVIEW

**Comment by lopsided98** [comment]
I don't think that is actually the right package. That looks like an unofficial client, while the rosdep key refers to the official client.

**Comment by lopsided98** [comment]
Also, the PR needs to go to upstream rosdep, not my fork.

**Comment by lopsided98** [comment]
In Ubuntu `libmongoclient-dev` is the mongo-cxx-driver legacy version (https://github.com/mongodb/mongo-cxx-driver/tree/releases/legacy). This is not packaged in nixpkgs, but the non-legacy version is packaged (only as of a few weeks ago) as `mongocxx`. The Fedora rosdep key appears to use this newer version, but this probably doesn't actually work. In particular, `warehouse_ros_mongo` appears to require the legacy version.

**Comment by GuillaumeDesforges** [comment]
You are right, I jumped too quickly. I found "libmongo-client" on nixpkgs (see the hyphen between mongo and client). :face_exhaling:

**Pull request closed without merging**
